--- Tests for ai-chat.context — Context tag parsing and collection
local context = require("ai-chat.context")

describe("context._parse_tags", function()
    it("parses a single @buffer tag", function()
        local tags = context._parse_tags("@buffer How do I fix this?")
        assert.equals(1, #tags)
        assert.equals("buffer", tags[1].name)
    end)

    it("parses multiple tags", function()
        local tags = context._parse_tags("@buffer @selection fix errors")
        assert.equals(2, #tags)
        assert.equals("buffer", tags[1].name)
        assert.equals("selection", tags[2].name)
    end)

    it("parses @file:path tag with args", function()
        local tags = context._parse_tags("@file:src/main.lua explain this")
        assert.equals(1, #tags)
        assert.equals("file", tags[1].name)
        assert.equals("src/main.lua", tags[1].args)
    end)

    it("parses @diff:staged tag", function()
        local tags = context._parse_tags("@diff:staged review my changes")
        assert.equals(1, #tags)
        assert.equals("diff", tags[1].name)
        assert.equals("staged", tags[1].args)
    end)

    it("returns empty for text with no tags", function()
        local tags = context._parse_tags("How do I fix this?")
        assert.equals(0, #tags)
    end)

    it("handles tags at different positions", function()
        local tags = context._parse_tags("explain @buffer this code @diagnostics")
        assert.equals(2, #tags)
        assert.equals("buffer", tags[1].name)
        assert.equals("diagnostics", tags[2].name)
    end)
end)

describe("context.strip_tags", function()
    it("strips a single tag", function()
        local result = context.strip_tags("@buffer How do I fix this?")
        assert.equals("How do I fix this?", result)
    end)

    it("strips multiple tags", function()
        local result = context.strip_tags("@buffer @selection How do I fix this?")
        assert.equals("How do I fix this?", result)
    end)

    it("strips @file:path tags", function()
        local result = context.strip_tags("@file:src/main.lua explain this")
        assert.equals("explain this", result)
    end)

    it("returns original text when no tags", function()
        local result = context.strip_tags("How do I fix this?")
        assert.equals("How do I fix this?", result)
    end)
end)

describe("context.available", function()
    it("returns a table of available context types", function()
        local available = context.available()
        assert.is_table(available)
        assert.is_true(#available > 0, "should have at least one context type")
    end)
end)
